# In _config.yml
title: Learning Deep Learning
author: Jack Roberts
logo: img/logo.png

execute:
  execute_notebooks: force
  timeout: 240

html:
  favicon: img/favicon.ico
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

repository:
  url: https://github.com/jack89roberts/learning-deep-learning
  branch: main

parse:
  myst_enable_extensions:  # extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist

