name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

permissions:
  contents: write

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install .
    
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Deploy to github pages 
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _build/html # The folder the action should deploy.
